---
- name: Play 1 - Install misl softwares and Apache
  hosts: webservers
  become: yes
  roles:
    - misl
    - apache

- name: Play 2 - Custom configuration of Apache
  hosts: webservers
  become: yes
  tasks:
    - name: "code copy"
      git:
        repo: 'https://github.com/mailrahulsre/learnwithprojects.com.git'
        dest: /var/www/html
        version: master
        force: yes


    - name: copy the proxypass file
      copy:
        src: /etc/ansible/lwplabs/proxypass.conf
        dest: /etc/httpd/conf.d/proxypass.conf
        owner: root
        group: root
      notify:
        - reload apache


    - name: selinux
      seboolean:
        name: httpd_can_network_connect
        state: yes
        persistent: yes
      tags: selinux

  handlers:
    - name: reload apache
      service: name=httpd state=reloaded
